import * as stylex from "@stylexjs/stylex"

const compactViewport = "@media (max-width: 48rem)"
const forcedColors = "@media (forced-colors: active)"

const previewStyles = stylex.create({
  route: {
    display: "grid",
    minHeight: "100svh",
    alignItems: "safe center",
    justifyItems: "safe center",
    overflowX: "hidden",
    overflowY: "auto",
    paddingTop: { default: "clamp(1rem, 4vw, 3rem)", [compactViewport]: "0.5rem" },
    paddingRight: { default: "clamp(1rem, 4vw, 3rem)", [compactViewport]: "0.5rem" },
    paddingBottom: { default: "clamp(1rem, 4vw, 3rem)", [compactViewport]: "0.5rem" },
    paddingLeft: { default: "clamp(1rem, 4vw, 3rem)", [compactViewport]: "0.5rem" },
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "transparent",
    backgroundImage: "radial-gradient(circle at 78% 18%, color-mix(in srgb, var(--gold-bright) 18%, transparent), transparent 30rem), linear-gradient(145deg, var(--paper-raised), var(--paper))",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
  },
  shell: {
    position: "relative",
    display: "grid",
    width: "min(100%, 54rem)",
    minHeight: {
      default: "min(38rem, calc(100svh - 2rem))",
      [compactViewport]: "calc(100svh - 1rem)",
    },
    alignContent: "center",
    paddingTop: { default: "clamp(1.5rem, 6vw, 5rem)", [compactViewport]: "clamp(1.25rem, 8vw, 2.5rem)" },
    paddingRight: { default: "clamp(1.5rem, 6vw, 5rem)", [compactViewport]: "clamp(1.25rem, 8vw, 2.5rem)" },
    paddingBottom: { default: "clamp(1.5rem, 6vw, 5rem)", [compactViewport]: "clamp(1.25rem, 8vw, 2.5rem)" },
    paddingLeft: { default: "clamp(1.5rem, 6vw, 5rem)", [compactViewport]: "clamp(1.25rem, 8vw, 2.5rem)" },
    borderColor: { default: "var(--line)", [forcedColors]: "CanvasText" },
    borderStyle: "solid",
    borderWidth: "1px",
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: 1,
    borderRadius: "0.875rem",
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "color-mix(in srgb, var(--paper-raised) 94%, transparent)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.06), 0 24px 48px -24px rgba(0, 0, 0, 0.28)",
  },
  mark: {
    position: "relative",
    width: "clamp(8rem, 24vw, 12rem)",
    height: "clamp(5rem, 15vw, 7.5rem)",
    marginBottom: "clamp(1.25rem, 4vw, 2.5rem)",
  },
  sun: {
    position: "absolute",
    top: 0,
    left: "50%",
    width: "clamp(3.75rem, 11vw, 5.5rem)",
    height: "clamp(3.75rem, 11vw, 5.5rem)",
    borderRadius: "50%",
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--gold-bright)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    boxShadow: "0 0 3rem color-mix(in srgb, var(--gold-bright) 38%, transparent)",
    transform: "translateX(-50%)",
  },
  path: {
    position: "absolute",
    right: 0,
    bottom: 0,
    left: 0,
    height: "55%",
    borderTopColor: "#bd4f2b",
    borderTopStyle: "solid",
    borderTopWidth: "2px",
    borderRadius: "50%",
    transform: "rotate(-7deg)",
  },
  kicker: {
    color: "var(--gold)",
    fontSize: "0.875rem",
    fontWeight: 500,
  },
  title: {
    marginTop: "0.25rem",
    fontSize: "clamp(4rem, 13vw, 8rem)",
    letterSpacing: "-0.04em",
    lineHeight: 0.95,
  },
  summary: {
    maxWidth: "34rem",
    marginTop: "clamp(1rem, 3vw, 1.75rem)",
    color: "var(--muted)",
    fontSize: "clamp(1.25rem, 3vw, 1.75rem)",
    lineHeight: 1.3,
  },
  outputs: {
    display: "grid",
    marginTop: "clamp(1.5rem, 5vw, 3rem)",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    borderBlockStartColor: "var(--line)",
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: "1px",
    borderBlockEndColor: "var(--line)",
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: "1px",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      [compactViewport]: "repeat(2, minmax(0, 1fr))",
    },
    listStyleType: "none",
    listStyleImage: "none",
    listStylePosition: "outside",
  },
  output: {
    display: "grid",
    minWidth: 0,
    gap: "0.2rem",
    paddingTop: "0.8rem",
    paddingRight: "clamp(0.55rem, 1.8vw, 1.1rem)",
    paddingBottom: "0.8rem",
    paddingLeft: "clamp(0.55rem, 1.8vw, 1.1rem)",
    fontSize: "clamp(0.8rem, 2vw, 1rem)",
  },
  followingOutput: {
    borderLeftColor: "var(--line)",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
  },
  thirdOutput: {
    borderLeftColor: { default: "var(--line)", [compactViewport]: "currentColor" },
    borderLeftStyle: { default: "solid", [compactViewport]: "none" },
    borderLeftWidth: { default: "1px", [compactViewport]: 0 },
  },
  lowerOutput: {
    borderTopColor: { default: null, [compactViewport]: "var(--line)" },
    borderTopStyle: { default: null, [compactViewport]: "solid" },
    borderTopWidth: { default: null, [compactViewport]: "1px" },
  },
  number: {
    color: "var(--gold)",
    fontFamily: "var(--font-mono)",
    fontSize: "0.7rem",
  },
  note: {
    marginTop: "0.85rem",
    color: "var(--muted)",
    fontSize: "0.8rem",
  },
})

export const previewClassNames = {
  route: stylex.props(previewStyles.route).className,
  shell: stylex.props(previewStyles.shell).className,
  mark: stylex.props(previewStyles.mark).className,
  sun: stylex.props(previewStyles.sun).className,
  path: stylex.props(previewStyles.path).className,
  kicker: stylex.props(previewStyles.kicker).className,
  title: stylex.props(previewStyles.title).className,
  summary: stylex.props(previewStyles.summary).className,
  outputs: stylex.props(previewStyles.outputs).className,
  firstOutput: stylex.props(previewStyles.output).className,
  secondOutput: stylex.props(previewStyles.output, previewStyles.followingOutput).className,
  thirdOutput: stylex.props(previewStyles.output, previewStyles.thirdOutput, previewStyles.lowerOutput).className,
  fourthOutput: stylex.props(previewStyles.output, previewStyles.followingOutput, previewStyles.lowerOutput).className,
  number: stylex.props(previewStyles.number).className,
  note: stylex.props(previewStyles.note).className,
} as const
