import { Effect } from "effect";
import { operationBoundary, runStandaloneOperation } from "../application/operation-effects";
import { executeAtomicRenderEffect, type AtomicRenderOutput } from "./atomic-render-effects";
import { AtomicRenderPlatformLive } from "./atomic-render-platform";
import type { ProcessRunner } from "./io";

export type { AtomicRenderOutput } from "./atomic-render-effects";

export async function executeAtomicRender(options: {
  readonly abortSignal?: AbortSignal;
  readonly argv: readonly [string, ...string[]];
  /**
   * Revalidates inputs after the subprocess exits but before generated bytes
   * receive their durable public name.
   */
  readonly beforePublish?: (output: AtomicRenderOutput) => Promise<void>;
  readonly companion?: {
    readonly finalPath: string;
    publish(output: AtomicRenderOutput): Promise<void>;
  };
  readonly failureLabel: string;
  readonly finalOutputPath: string;
  readonly maximumOutputBytes: number;
  /**
   * Publishes with an atomic hard link so a destination created while the
   * renderer runs is never replaced.
   */
  readonly requireFreshOutput?: boolean;
  readonly runner: ProcessRunner;
  /**
   * Optional host-owned private workspace for generated bytes. Workflow
   * callers use this so FFmpeg never writes a temporary beside a public
   * output; legacy CLI callers retain the final-output directory default.
   */
  readonly stagingDirectory?: string;
  readonly timeoutMs?: number;
}): Promise<AtomicRenderOutput> {
  const companion = options.companion;
  const result = await runStandaloneOperation(executeAtomicRenderEffect(options, {
    prepare: output => operationBoundary("publication", () => options.beforePublish?.(output)),
    ...(companion === undefined ? {} : {
      companion: {
        finalPath: companion.finalPath,
        publish: (_prepared: void, output: AtomicRenderOutput) =>
          operationBoundary("publication", () => companion.publish(output)),
      },
    }),
  }).pipe(Effect.provide(AtomicRenderPlatformLive)));
  return result.output;
}
