import { createHash, randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { link, lstat, open, realpath, rename, rm } from "node:fs/promises";
import { dirname, extname, join } from "node:path";

import { CliError, errorMessage } from "./errors";
import type { ProcessRunner } from "./io";

export interface AtomicRenderOutput {
  readonly bytes: number;
  readonly sha256: string;
}

const OUTPUT_GROWTH_POLL_MILLISECONDS = 10;

function missingFile(error: unknown): boolean {
  return (
    error instanceof Error
    && "code" in error
    && error.code === "ENOENT"
  );
}

async function waitForOutputGrowthPoll(signal: AbortSignal): Promise<void> {
  if (signal.aborted) return;
  await new Promise<void>(resolveWait => {
    let settled = false;
    const settle = (): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      signal.removeEventListener("abort", settle);
      resolveWait();
    };
    const timer = setTimeout(settle, OUTPUT_GROWTH_POLL_MILLISECONDS);
    signal.addEventListener("abort", settle, { once: true });
    if (signal.aborted) settle();
  });
}

async function monitorAtomicRenderOutput(options: {
  readonly maximumOutputBytes: number;
  readonly path: string;
  readonly signal: AbortSignal;
  readonly tooLarge: (observedBytes: number) => void;
}): Promise<void> {
  while (!options.signal.aborted) {
    try {
      const details = await lstat(options.path);
      if (details.size > options.maximumOutputBytes) {
        options.tooLarge(details.size);
        return;
      }
    } catch (error) {
      if (!missingFile(error)) throw error;
    }
    await waitForOutputGrowthPoll(options.signal);
  }
}

async function syncDirectory(path: string): Promise<void> {
  const directory = await open(path, constants.O_RDONLY);
  try {
    await directory.sync();
  } finally {
    await directory.close();
  }
}

export async function executeAtomicRender(options: {
  readonly abortSignal?: AbortSignal;
  readonly argv: readonly [string, ...string[]];
  /**
   * Revalidates inputs after the subprocess exits but before generated bytes
   * receive their durable public name.
   */
  readonly beforePublish?: (output: AtomicRenderOutput) => Promise<void>;
  readonly companion?: {
    readonly finalPath: string;
    publish(output: AtomicRenderOutput): Promise<void>;
  };
  readonly failureLabel: string;
  readonly finalOutputPath: string;
  readonly maximumOutputBytes: number;
  /**
   * Publishes with an atomic hard link so a destination created while the
   * renderer runs is never replaced.
   */
  readonly requireFreshOutput?: boolean;
  readonly runner: ProcessRunner;
  /**
   * Optional host-owned private workspace for generated bytes. Workflow
   * callers use this so FFmpeg never writes a temporary beside a public
   * output; legacy CLI callers retain the final-output directory default.
   */
  readonly stagingDirectory?: string;
  readonly timeoutMs?: number;
}): Promise<AtomicRenderOutput> {
  if (options.argv.at(-1) !== options.finalOutputPath) {
    throw new CliError("internal", "Render invocation output does not match its requested final path.");
  }
  if (options.companion?.finalPath === options.finalOutputPath) {
    throw new CliError("internal", "Render output and companion paths must be distinct.");
  }
  if (
    !Number.isSafeInteger(options.maximumOutputBytes)
    || options.maximumOutputBytes < 1
  ) {
    throw new CliError("invalid-data", "Render output byte limit must be a positive safe integer.");
  }
  const extension = extname(options.finalOutputPath) || ".media";
  let temporaryDirectory = dirname(options.finalOutputPath);
  if (options.stagingDirectory !== undefined) {
    const staging = await lstat(options.stagingDirectory);
    if (
      staging.isSymbolicLink()
      || !staging.isDirectory()
      || (staging.mode & 0o077) !== 0
    ) {
      throw new CliError(
        "unsafe-path",
        "Atomic render staging must be a private physical directory.",
      );
    }
    temporaryDirectory = await realpath(options.stagingDirectory);
  }
  const temporary = join(temporaryDirectory, `.atet-render-${randomUUID()}.tmp${extension}`);
  let output: AtomicRenderOutput | undefined;
  try {
    const argv = [...options.argv] as [string, ...string[]];
    const overwriteIndex = argv.indexOf("-y");
    if (overwriteIndex < 0) {
      throw new CliError("internal", "Atomic render invocation must contain FFmpeg's overwrite flag.");
    }
    // Leave the random path absent and require exclusive FFmpeg creation. A
    // prepositioned symlink or hard link then fails before any target is opened.
    argv[overwriteIndex] = "-n";
    argv[argv.length - 1] = temporary;
    const rendererAbort = new AbortController();
    const monitorAbort = new AbortController();
    let observedOversizedOutput: number | undefined;
    let monitorFailure: unknown;
    const forwardCallerAbort = (): void => {
      rendererAbort.abort(options.abortSignal?.reason);
    };
    options.abortSignal?.addEventListener("abort", forwardCallerAbort, { once: true });
    if (options.abortSignal?.aborted === true) forwardCallerAbort();
    const monitor = monitorAtomicRenderOutput({
      maximumOutputBytes: options.maximumOutputBytes,
      path: temporary,
      signal: monitorAbort.signal,
      tooLarge: observedBytes => {
        observedOversizedOutput = observedBytes;
        rendererAbort.abort(new CliError(
          "invalid-data",
          "Renderer output exceeded its configured byte limit while encoding.",
        ));
      },
    }).catch(error => {
      monitorFailure = error;
      rendererAbort.abort(error);
    });
    // Observe the monitor immediately. The awaited settlement below still
    // receives the same failure after ProcessRunner has killed and reaped.
    void monitor.catch(() => undefined);
    let result: Awaited<ReturnType<ProcessRunner["run"]>>;
    try {
      result = await options.runner.run(argv, {
        abortSignal: rendererAbort.signal,
        maxOutputBytes: 1_000_000,
        ...(options.timeoutMs === undefined
          ? {}
          : { timeoutMs: options.timeoutMs }),
      });
    } catch (error) {
      if (observedOversizedOutput !== undefined) {
        throw new CliError(
          "invalid-data",
          `Renderer output exceeded its configured ${String(options.maximumOutputBytes)}-byte limit while encoding (${String(observedOversizedOutput)} bytes observed).`,
        );
      }
      if (monitorFailure !== undefined) {
        throw new CliError(
          "unavailable",
          `Renderer output could not be monitored safely: ${errorMessage(monitorFailure)}`,
        );
      }
      throw error;
    } finally {
      monitorAbort.abort();
      await monitor;
      options.abortSignal?.removeEventListener("abort", forwardCallerAbort);
    }
    if (observedOversizedOutput !== undefined) {
      throw new CliError(
        "invalid-data",
        `Renderer output exceeded its configured ${String(options.maximumOutputBytes)}-byte limit while encoding (${String(observedOversizedOutput)} bytes observed).`,
      );
    }
    if (monitorFailure !== undefined) {
      throw new CliError(
        "unavailable",
        `Renderer output could not be monitored safely: ${errorMessage(monitorFailure)}`,
      );
    }
    if (result.exitCode !== 0) {
      throw new CliError(
        "subprocess",
        `${options.failureLabel}: ${result.stderr.trim().slice(-4_000) || `exit ${result.exitCode}`}`,
      );
    }
    const lexical = await lstat(temporary);
    if (lexical.isSymbolicLink() || !lexical.isFile() || lexical.size <= 0 || lexical.nlink !== 1) {
      throw new CliError("invalid-data", "Renderer produced an unsafe, empty, or multiply-linked output file.");
    }
    if (lexical.size > options.maximumOutputBytes) {
      throw new CliError(
        "invalid-data",
        "Renderer output exceeds its configured byte limit.",
      );
    }
    const handle = await open(temporary, constants.O_RDWR | constants.O_NOFOLLOW);
    try {
      const opened = await handle.stat();
      if (
        !opened.isFile()
        || opened.dev !== lexical.dev
        || opened.ino !== lexical.ino
        || opened.size !== lexical.size
        || opened.nlink !== 1
      ) {
        throw new CliError("conflict", "Render output changed before it could be committed.");
      }
      await handle.chmod(0o600);
      await handle.sync();
      const beforeHash = await handle.stat();
      if (
        beforeHash.size !== opened.size
        || beforeHash.dev !== opened.dev
        || beforeHash.ino !== opened.ino
        || beforeHash.nlink !== 1
        || !Number.isSafeInteger(beforeHash.size)
      ) {
        throw new CliError("conflict", "Render output changed while it was being committed.");
      }
      const hash = createHash("sha256");
      const buffer = Buffer.allocUnsafe(1024 * 1024);
      let bytes = 0;
      while (bytes < beforeHash.size) {
        const read = await handle.read(buffer, 0, Math.min(buffer.byteLength, beforeHash.size - bytes), bytes);
        if (read.bytesRead === 0) break;
        hash.update(buffer.subarray(0, read.bytesRead));
        bytes += read.bytesRead;
      }
      const afterHash = await handle.stat();
      if (
        bytes !== beforeHash.size
        || afterHash.size !== beforeHash.size
        || afterHash.dev !== beforeHash.dev
        || afterHash.ino !== beforeHash.ino
        || afterHash.nlink !== 1
        || afterHash.mtimeMs !== beforeHash.mtimeMs
        || afterHash.ctimeMs !== beforeHash.ctimeMs
      ) {
        throw new CliError("conflict", "Render output changed while its integrity was being recorded.");
      }
      output = { bytes, sha256: hash.digest("hex") };
    } finally {
      await handle.close();
    }
    await options.beforePublish?.(output);
    if (options.companion !== undefined) {
      // Invalidate the old receipt durably before committing new bytes. A
      // crash may then leave no receipt, but can never leave stale metadata
      // that appears to authenticate the newly committed output.
      await rm(options.companion.finalPath, { force: true });
      await syncDirectory(dirname(options.companion.finalPath));
    }
    if (options.requireFreshOutput === true) {
      try {
        await link(temporary, options.finalOutputPath);
      } catch (error) {
        if (
          error instanceof Error
          && "code" in error
          && error.code === "EEXIST"
        ) {
          throw new CliError(
            "conflict",
            `Render output was created concurrently: ${options.finalOutputPath}`,
          );
        }
        throw error;
      }
      await rm(temporary);
    } else {
      await rename(temporary, options.finalOutputPath);
    }
    await syncDirectory(dirname(options.finalOutputPath));
    if (options.companion !== undefined) {
      try {
        await options.companion.publish(output);
      } catch (error) {
        // A stale companion is worse than no companion: without this removal,
        // the old metadata could falsely claim the newly committed video.
        await rm(options.companion.finalPath, { force: true });
        await syncDirectory(dirname(options.companion.finalPath));
        throw error;
      }
    }
    return output;
  } finally {
    await rm(temporary, { force: true });
  }
}
