import { describe, expect, spyOn, test } from "bun:test";
import * as fileSystem from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { createFileGatewayMediaArtifactStore } from "./gateway-media-artifacts";

const {
  mkdtemp,
  readFile,
  readdir,
  rm,
  stat,
  symlink,
} = fileSystem;

const PNG_BYTES = Uint8Array.of(
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a,
);
const JPEG_BYTES = Uint8Array.of(0xff, 0xd8, 0xff);
const WAV_BYTES = new TextEncoder().encode("RIFF\u0000\u0000\u0000\u0000WAVE");
const ROUTING = {
  attemptCount: 0,
  attempts: [],
  attemptsTruncated: false,
  clientMaxRetries: 0,
  gatewayProviderFailover: "may-attempt-multiple-providers",
  providerCount: 0,
  providers: [],
  providersTruncated: false,
} as const;
const SIGNAL = new AbortController().signal;

async function rejection(promise: Promise<unknown>): Promise<unknown> {
  try {
    await promise;
  } catch (error) {
    return error;
  }
  throw new Error("Expected promise rejection.");
}

describe("Gateway media artifact store", () => {
  test("rejects relative output roots before creating a store", () => {
    expect(() => createFileGatewayMediaArtifactStore({
      outputRoot: "artifacts/atet/generated",
      repositoryRoot: "/repository",
    })).toThrow();
  });

  test("publishes generated bytes and their integrity receipt as one atomic directory", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-output-"));
    try {
      const outputRoot = join(temporary, "generated");
      const store = createFileGatewayMediaArtifactStore({
        outputRoot,
        randomId: () => "fixed1234",
        repositoryRoot: temporary,
        validateMediaFile: () => Promise.resolve(),
      });
      const bundle = await store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [
          { mediaType: "image/png", uint8Array: PNG_BYTES },
          { mediaType: "image/jpeg", uint8Array: JPEG_BYTES },
        ],
        inputs: [{
          bytes: 1,
          mediaType: "image/png",
          role: "reference.1",
          sha256: "b".repeat(64),
          source: "inline",
        }],
        mediaKind: "image",
        model: "bfl/flux",
        operation: "image.generate",
        request: {
          promptSha256: "c".repeat(64),
          providerOptionsSha256: "d".repeat(64),
        },
        routing: ROUTING,
        signal: SIGNAL,
        warnings: ["setting unsupported"],
      });

      expect(await readdir(outputRoot)).toEqual([
        "20260723T120000000Z-image-fixed1234",
      ]);
      expect(bundle.outputs.map(output => ({
        bytes: output.bytes,
        file: output.file,
        mediaType: output.mediaType,
        sha256: output.sha256,
      }))).toEqual([
        {
          bytes: 8,
          file: "image-01.png",
          mediaType: "image/png",
          sha256: "4c4b6a3be1314ab86138bef4314dde022e600960d8689a2c8f8631802d20dab6",
        },
        {
          bytes: 3,
          file: "image-02.jpg",
          mediaType: "image/jpeg",
          sha256: "6e568e1f67fba258184c78181539e5e8fdee447e49bb706fc0ea34fbf12336a5",
        },
      ]);
      const receiptSource = await readFile(bundle.receiptPath, "utf8");
      expect(JSON.parse(receiptSource)).toEqual(bundle.receipt);
      expect(bundle.receipt.kind).toBe("atet.gateway-media-receipt");
      expect(receiptSource).not.toContain("provider secret");
      expect(receiptSource).not.toContain(temporary);
      expect(bundle.receipt.nextCommands).toEqual([
        "atet project add <project> generated/20260723T120000000Z-image-fixed1234/image-01.png --role b-roll",
        "atet project add <project> generated/20260723T120000000Z-image-fixed1234/image-02.jpg --role b-roll",
      ]);
      expect(bundle.receipt.localValidation).toEqual({
        decodeValidatedOutputs: 2,
        signatureOnlyOutputs: 0,
        status: "decode-passed",
      });
      for (const path of [bundle.receiptPath, ...bundle.outputs.map(output => output.path)]) {
        expect((await stat(path)).mode & 0o777).toBe(0o600);
      }
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("rechecks the workflow fence at the final atomic publication boundary", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-fence-"));
    try {
      const outputRoot = join(temporary, "generated");
      const finalName = "20260723T120000000Z-image-fence1234";
      let fenceCalls = 0;
      const store = createFileGatewayMediaArtifactStore({
        beforePublication: async () => {
          fenceCalls += 1;
          expect(await readdir(outputRoot)).toEqual([`.${finalName}.tmp`]);
          throw new Error("workflow was cancelled before publication");
        },
        outputRoot,
        randomId: () => "fence1234",
        repositoryRoot: temporary,
      });
      expect(store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [{ mediaType: "image/png", uint8Array: PNG_BYTES }],
        inputs: [],
        mediaKind: "image",
        model: "bfl/flux",
        operation: "image.generate",
        request: {},
        routing: ROUTING,
        signal: SIGNAL,
        warnings: [],
      })).rejects.toMatchObject({ code: "artifact-unavailable" });
      expect(fenceCalls).toBe(1);
      expect(await readdir(outputRoot)).toEqual([]);
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("returns the committed bundle when cancellation lands after atomic publication", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-committed-"));
    const controller = new AbortController();
    const originalRename = fileSystem.rename;
    const renameSpy = spyOn(fileSystem, "rename").mockImplementation(
      async (source, destination) => {
        await originalRename(source, destination);
        controller.abort(new Error("fixture cancelled after publication"));
      },
    );
    try {
      const outputRoot = join(temporary, "generated");
      const store = createFileGatewayMediaArtifactStore({
        outputRoot,
        randomId: () => "committed1234",
        repositoryRoot: temporary,
      });
      const bundle = await store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [{ mediaType: "image/png", uint8Array: PNG_BYTES }],
        inputs: [],
        mediaKind: "image",
        model: "bfl/flux",
        operation: "image.generate",
        request: {},
        routing: ROUTING,
        signal: controller.signal,
        warnings: [],
      });

      expect(controller.signal.aborted).toBe(true);
      expect(renameSpy).toHaveBeenCalledTimes(1);
      expect(await readdir(outputRoot)).toEqual([
        "20260723T120000000Z-image-committed1234",
      ]);
      expect(await readFile(bundle.receiptPath, "utf8"))
        .toContain('"kind":"atet.gateway-media-receipt"');
    } finally {
      renameSpy.mockRestore();
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("rejects a symlinked output root before writing generated bytes", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-output-link-"));
    try {
      const destination = join(temporary, "destination");
      const link = join(temporary, "generated");
      await Bun.write(join(destination, ".keep"), "");
      await symlink(destination, link, "dir");
      const store = createFileGatewayMediaArtifactStore({
        outputRoot: link,
        randomId: () => "fixed1234",
        repositoryRoot: temporary,
      });
      expect(store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [{ mediaType: "image/png", uint8Array: PNG_BYTES }],
        inputs: [],
        mediaKind: "image",
        model: "bfl/flux",
        operation: "image.generate",
        request: {},
        routing: ROUTING,
        signal: SIGNAL,
        warnings: [],
      })).rejects.toMatchObject({ code: "unsafe-output" });
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("rejects mislabeled and active generated media at the persistence boundary", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-invalid-output-"));
    try {
      const store = createFileGatewayMediaArtifactStore({
        outputRoot: join(temporary, "generated"),
        randomId: () => "invalid1234",
        repositoryRoot: temporary,
      });
      const base = {
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" as const },
        createdAt: "2026-07-23T12:00:00.000Z",
        inputs: [],
        mediaKind: "image" as const,
        model: "bfl/flux",
        operation: "image.generate" as const,
        request: {},
        routing: ROUTING,
        signal: SIGNAL,
        warnings: [],
      };
      expect(store.commit({
        ...base,
        files: [{
          mediaType: "image/png",
          uint8Array: new TextEncoder().encode("not a png"),
        }],
      })).rejects.toMatchObject({ code: "artifact-invalid" });
      expect(store.commit({
        ...base,
        files: [{
          mediaType: "image/svg+xml",
          uint8Array: new TextEncoder().encode("<svg/>"),
        }],
      })).rejects.toMatchObject({ code: "artifact-invalid" });
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("uses agent-friendly transcript extensions for every output format", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-transcript-"));
    try {
      const store = createFileGatewayMediaArtifactStore({
        outputRoot: join(temporary, "generated"),
        randomId: () => "formats1234",
        repositoryRoot: temporary,
      });
      const bundle = await store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [
          { mediaType: "application/json", uint8Array: Uint8Array.of(123, 125) },
          { mediaType: "text/plain", uint8Array: Uint8Array.of(120) },
          { mediaType: "application/x-subrip", uint8Array: Uint8Array.of(120) },
          { mediaType: "text/vtt", uint8Array: Uint8Array.of(120) },
        ],
        inputs: [],
        mediaKind: "transcription",
        model: "openai/whisper-1",
        operation: "transcription.create",
        request: {},
        routing: ROUTING,
        signal: SIGNAL,
        warnings: [],
      });
      expect(bundle.outputs.map(output => output.file)).toEqual([
        "transcript-01.json",
        "transcript-02.txt",
        "transcript-03.srt",
        "transcript-04.vtt",
      ]);
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("does not recommend importing headerless speech as project dialogue", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-speech-"));
    try {
      const store = createFileGatewayMediaArtifactStore({
        outputRoot: join(temporary, "generated"),
        randomId: () => "speech1234",
        repositoryRoot: temporary,
        validateMediaFile: () => Promise.resolve(),
      });
      const bundle = await store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [
          { mediaType: "audio/pcm", uint8Array: Uint8Array.of(0, 0) },
          { mediaType: "audio/l16", uint8Array: Uint8Array.of(0, 0) },
          { mediaType: "audio/alaw", uint8Array: Uint8Array.of(0) },
          { mediaType: "audio/basic", uint8Array: Uint8Array.of(0) },
          { mediaType: "audio/mulaw", uint8Array: Uint8Array.of(0) },
          { mediaType: "audio/wav", uint8Array: WAV_BYTES },
        ],
        inputs: [],
        mediaKind: "speech",
        model: "openai/tts-1",
        operation: "speech.generate",
        request: {},
        routing: ROUTING,
        signal: SIGNAL,
        warnings: [],
      });

      expect(bundle.receipt.nextCommands).toEqual([
        "atet project add <project> generated/20260723T120000000Z-speech-speech1234/speech-06.wav --role dialogue",
      ]);
      expect(bundle.receipt.localValidation).toEqual({
        decodeValidatedOutputs: 1,
        signatureOnlyOutputs: 5,
        status: "decode-passed",
      });
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("cancels a non-settling decode before publication and reclaims staging", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-cancel-"));
    try {
      const controller = new AbortController();
      const outputRoot = join(temporary, "generated");
      let activeValidations = 0;
      let beforePublicationCalls = 0;
      let receivedSignal: AbortSignal | undefined;
      let validationStartedResolve: (() => void) | undefined;
      const validationStarted = new Promise<void>((resolve) => {
        validationStartedResolve = resolve;
      });
      const store = createFileGatewayMediaArtifactStore({
        beforePublication: () => {
          beforePublicationCalls += 1;
          return Promise.resolve();
        },
        outputRoot,
        randomId: () => "cancel1234",
        repositoryRoot: temporary,
        validateMediaFile: (_file, signal) => {
          receivedSignal = signal;
          activeValidations += 1;
          validationStartedResolve?.();
          return new Promise((_resolve, reject) => {
            const abort = (): void => {
              activeValidations -= 1;
              reject(new Error("fixture decode cancelled"));
            };
            if (signal.aborted) abort();
            else signal.addEventListener("abort", abort, { once: true });
          });
        },
      });
      const pending = store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [{ mediaType: "image/png", uint8Array: PNG_BYTES }],
        inputs: [],
        mediaKind: "image",
        model: "bfl/flux",
        operation: "image.generate",
        request: {},
        routing: ROUTING,
        signal: controller.signal,
        warnings: [],
      });

      await validationStarted;
      controller.abort(new Error("fixture operation deadline"));
      expect(await rejection(pending)).toMatchObject({
        message: "fixture operation deadline",
      });
      expect(receivedSignal).toBe(controller.signal);
      expect(activeValidations).toBe(0);
      expect(beforePublicationCalls).toBe(0);
      expect(await readdir(outputRoot)).toEqual([]);
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });

  test("preserves paid bytes without import commands when decode validation fails", async () => {
    const temporary = await mkdtemp(join(tmpdir(), "atet-gateway-quarantine-"));
    try {
      const store = createFileGatewayMediaArtifactStore({
        outputRoot: join(temporary, "generated"),
        randomId: () => "failed1234",
        repositoryRoot: temporary,
        validateMediaFile: () => Promise.reject(
          new Error("decoder exposed secret provider body"),
        ),
      });
      const bundle = await store.commit({
        catalog: { snapshotId: `sha256:${"a".repeat(64)}`, status: "fresh" },
        createdAt: "2026-07-23T12:00:00.000Z",
        files: [{ mediaType: "image/png", uint8Array: PNG_BYTES }],
        inputs: [],
        mediaKind: "image",
        model: "bfl/flux",
        operation: "image.generate",
        request: {},
        routing: ROUTING,
        signal: SIGNAL,
        warnings: [],
      });
      expect(bundle.receipt.localValidation).toMatchObject({
        decodeValidatedOutputs: 0,
        signatureOnlyOutputs: 0,
        status: "decode-failed",
      });
      expect(bundle.receipt.localValidation.failureSha256)
        .toMatch(/^[a-f0-9]{64}$/u);
      expect(bundle.receipt.nextCommands).toEqual([]);
      expect(await readFile(bundle.outputs[0]!.path)).toEqual(
        Buffer.from(PNG_BYTES),
      );
      expect(JSON.stringify(bundle.receipt))
        .not.toContain("decoder exposed secret provider body");
    } finally {
      await rm(temporary, { force: true, recursive: true });
    }
  });
});
